unpackaged/main/default/objects/Account/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ag/Chem Manufacturer</fullName>
            </value>
            <value>
                <fullName>Ag Input Retailer/Distributor</fullName>
            </value>
            <value>
                <fullName>CPG (Manufacturer)</fullName>
            </value>
            <value>
                <fullName>Crop Consultants</fullName>
            </value>
            <value>
                <fullName>Crop Insurance</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Equipment Company</fullName>
            </value>
            <value>
                <fullName>ERP Management</fullName>
            </value>
            <value>
                <fullName>Farm</fullName>
            </value>
            <value>
                <fullName>ISV (Independent software vendor)</fullName>
            </value>
            <value>
                <fullName>Lab Company</fullName>
            </value>
            <value>
                <fullName>Ranch</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Sales Agency/ Food Broker</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sub_Industry__c.field-meta.xml
<CustomField>
    <fullName>Sub_Industry__c</fullName>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Applicator</fullName>
            </value>
            <value>
                <fullName>3rd Party Sampler</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Aggregator</fullName>
            </value>
            <value>
                <fullName>Agronomist</fullName>
            </value>
            <value>
                <fullName>AIP (Approved Insurance Provider)</fullName>
            </value>
            <value>
                <fullName>Beef producer</fullName>
            </value>
            <value>
                <fullName>Chemical Manufacturer</fullName>
            </value>
            <value>
                <fullName>Co-Operative</fullName>
            </value>
            <value>
                <fullName>Custom Services</fullName>
            </value>
            <value>
                <fullName>Dairy producer</fullName>
            </value>
            <value>
                <fullName>Distributor/Logistics</fullName>
            </value>
            <value>
                <fullName>Equipment Dealer</fullName>
            </value>
            <value>
                <fullName>Equipment Manufacturer</fullName>
            </value>
            <value>
                <fullName>Farm Mgmt Company</fullName>
            </value>
            <value>
                <fullName>Fertilizer Manufacturer</fullName>
            </value>
            <value>
                <fullName>Financial &amp; Banking</fullName>
            </value>
            <value>
                <fullName>FMIS (Farm Management Information System)</fullName>
            </value>
            <value>
                <fullName>Food Retailer</fullName>
            </value>
            <value>
                <fullName>Full Service Location</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Hedge-Fund/Investment Company</fullName>
            </value>
            <value>
                <fullName>High Value Crop Grower</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Lab Company</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
            <value>
                <fullName>Permanent Crop Grower</fullName>
            </value>
            <value>
                <fullName>Precision Consultant</fullName>
            </value>
            <value>
                <fullName>Processor</fullName>
            </value>
            <value>
                <fullName>Restaurants/Quick Serve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agri-Business</fullName>
            </value>
            <value>
                <fullName>Agri-Food</fullName>
            </value>
            <value>
                <fullName>Farm &amp; Ranch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name__c</fullName>
    <description>created for TAGCRM-128</description>
    <label>Competitor(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Survey Based Market Research(Kynetec)</fullName>
            </value>
            <value>
                <fullName>Survey Based Market Research(SPC)</fullName>
            </value>
            <value>
                <fullName>Premier Crop</fullName>
            </value>
            <value>
                <fullName>IN10T</fullName>
            </value>
            <value>
                <fullName>In-House Built Systems</fullName>
            </value>
            <value>
                <fullName>DCI</fullName>
            </value>
            <value>
                <fullName>AgCall</fullName>
            </value>
            <value>
                <fullName>Beck Ag</fullName>
            </value>
            <value>
                <fullName>AgData</fullName>
            </value>
            <value>
                <fullName>AgriTrend</fullName>
            </value>
            <value>
                <fullName>Smartwyre</fullName>
            </value>
            <value>
                <fullName>Aker</fullName>
            </value>
            <value>
                <fullName>Farmers Edge</fullName>
            </value>
            <value>
                <fullName>Taranis</fullName>
            </value>
            <value>
                <fullName>Decisive Farming</fullName>
            </value>
            <value>
                <fullName>Climate</fullName>
            </value>
            <value>
                <fullName>Retail FMS Systems</fullName>
            </value>
            <value>
                <fullName>One Soil</fullName>
            </value>
            <value>
                <fullName>EOS</fullName>
            </value>
            <value>
                <fullName>Authenticate</fullName>
            </value>
            <value>
                <fullName>FoodLogic</fullName>
            </value>
            <value>
                <fullName>Quadex</fullName>
            </value>
            <value>
                <fullName>iAuditor and Excel</fullName>
            </value>
            <value>
                <fullName>Excel</fullName>
            </value>
            <value>
                <fullName>ERP Systems</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>TraceOne</fullName>
            </value>
            <value>
                <fullName>Agriplace</fullName>
            </value>
            <value>
                <fullName>Food Experts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cycle_Time_SIT_1_to_Closed__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Time_SIT_1_to_Closed__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Days b/w SIT 1 to closed stage</description>
    <inlineHelpText>Days b/w SIT 1 to SIT 5 stage</inlineHelpText>
    <label>Cycle Time  SIT 1 to Closed</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cycle_Time_SIT_2_to_SIT_1__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Time_SIT_2_to_SIT_1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>created for TAGCRM-181</description>
    <inlineHelpText>Days b/w SIT 2 to SIT 1 stage</inlineHelpText>
    <label>Cycle Time  SIT 2 to SIT 1</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cycle_Time_SIT_3_to_SIT_2__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Time_SIT_3_to_SIT_2__c</fullName>
    <defaultValue>0</defaultValue>
    <description>created for TAGCRM-181</description>
    <inlineHelpText>Days b/w SIT 3 to SIT 2 stage</inlineHelpText>
    <label>Cycle Time  SIT 3 to SIT 2</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cycle_Time_SIT_4_to_SIT_3__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Time_SIT_4_to_SIT_3__c</fullName>
    <defaultValue>0</defaultValue>
    <description>created for TAGCRM-181</description>
    <inlineHelpText>Days b/w SIT 4 to SIT 3 stage</inlineHelpText>
    <label>Cycle Time  SIT 4 to SIT 3</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cycle_Time_SIT_5_to_SIT_4__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Time_SIT_5_to_SIT_4__c</fullName>
    <defaultValue>0</defaultValue>
    <description>created for TAGCRM-181</description>
    <inlineHelpText>Days b/w SIT 5 to SIT 4 stage</inlineHelpText>
    <label>Cycle Time  SIT 5 to SIT 4</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cycle_Time_SIT_6_to_SIT_5__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Time_SIT_6_to_SIT_5__c</fullName>
    <defaultValue>0</defaultValue>
    <description>created for TAGCRM-181</description>
    <inlineHelpText>Days b/w SIT 6 to SIT 5 stage</inlineHelpText>
    <label>Cycle Time  SIT 6 to SIT 5</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <description>Name of the Project</description>
    <label>Project Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <description>This field contains the vertical (market segment) from the associated Account record.</description>
    <formula>TEXT(Account.Vertical__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field contains the vertical (market segment) from the associated Account record.</inlineHelpText>
    <label>Vertical</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/trac_TestDataFactory.cls
/**
*******************************************************************************
* trac_TestDataFactory  part of the Telus Agri project
* @description this class contains setup data for all the test classes
* @author Neha Jain, Traction on Demand
* @date 2020-12-18
*
*******************************************************************************
*/

@isTest
public class trac_TestDataFactory {

/**
    * @description this method used to create test Account records
    * @param numberOfRecords - Integer, the no. of records need to be created
    * @param isInsert - Boolean, the records need to be inserted or not
    * @param fieldValueByFieldName - Map<String,String>, field value by field name for Account records to be created
    * @return listOfTestAccounts - List<Account>, list of inserted Account records
    */
    public static List<Account> createTestAccounts(Integer numberOfRecords, Boolean isInsert,Map<String, String> fieldValueByFieldName) {
        List<Account> listOfTestAccounts = new List<Account>();

        for(Integer i=0; i<numberOfRecords; i++) {
            Account account = new Account();
            account.Name = getFieldValues(fieldValueByFieldName, 'Name', 'Test Account' + i);
            account.Type = getFieldValues(fieldValueByFieldName, 'Type', 'Analyst');
            account.Website = getFieldValues(fieldValueByFieldName, 'Website', 'www.Testwebsite.com');
            account.Sub_Industry__c = getFieldValues(fieldValueByFieldName, 'Sub_Industry__c', '3rd Party Applicator');
            account.Industry__c = getFieldValues(fieldValueByFieldName, 'Industry__c', 'Equipment Company');
            account.Vertical__c = getFieldValues(fieldValueByFieldName, 'Vertical__c', 'Agri-Business');
            listOfTestAccounts.add(account);
        }
        if(isInsert) {
            insert listOfTestAccounts;
        }

        return listOfTestAccounts;
    }

    /**
    * @description this method used to create test Opportunity records
    * @param numberOfRecords - Integer, the no. of records need to be created
    * @param isInsert - Boolean, the records need to be inserted or not
    * @param fieldValueByFieldName - Map<String,String>, field value by field name for Opportunity records to be created
    * @param listOfContacts - List<Contact>, list of Contacts used for lookup field 'Position_Reports_To__c'
    * @param recordTypeName - String, RecordType name for Opportunity
    * @return listOfTestOpportunities - List<Opportunity>, list of inserted Opportunity records
    */
    public static List<Opportunity> createTestOpportunities(Integer numberOfRecords, Boolean isInsert,
            Map<String, String> fieldValueByFieldName, List<Account> listOfAccounts,Map<String, Decimal> cycleTimeMap) {
        List<Opportunity> listOfTestOpportunities = new List<Opportunity>();

        for(Integer i=0; i<numberOfRecords; i++) {
            Opportunity opp = new Opportunity();
            opp.Name = getFieldValues(fieldValueByFieldName, 'Name', 'Test Opportunity' + i);
            opp.CloseDate = System.today() + 12 ;
            opp.StageName = getFieldValues(fieldValueByFieldName, 'StageName', trac_Constants.OPP_STAGE_SIT6_REPOSITORY) ;
            if(cycleTimeMap.containsKey('Cycle_Time_SIT_6_to_SIT_5__c')){
                opp.Cycle_Time_SIT_6_to_SIT_5__c = cycleTimeMap.get('Cycle_Time_SIT_6_to_SIT_5__c');
            }
            if(cycleTimeMap.containsKey('Cycle_Time_SIT_5_to_SIT_4__c')){
                opp.Cycle_Time_SIT_5_to_SIT_4__c = cycleTimeMap.get('Cycle_Time_SIT_5_to_SIT_4__c');
            }
            if(cycleTimeMap.containsKey('Cycle_Time_SIT_4_to_SIT_3__c')){
                opp.Cycle_Time_SIT_4_to_SIT_3__c = cycleTimeMap.get('Cycle_Time_SIT_4_to_SIT_3__c');
            }
            if(cycleTimeMap.containsKey('Cycle_Time_SIT_3_to_SIT_2__c')){
                opp.Cycle_Time_SIT_3_to_SIT_2__c = cycleTimeMap.get('Cycle_Time_SIT_3_to_SIT_2__c');
            }
            if(cycleTimeMap.containsKey('Cycle_Time_SIT_2_to_SIT_1__c')){
                opp.Cycle_Time_SIT_2_to_SIT_1__c = cycleTimeMap.get('Cycle_Time_SIT_2_to_SIT_1__c');
                opp.Competitor_Name__c = 'DCI';
            }
            if(cycleTimeMap.containsKey('Cycle_Time_SIT_1_to_Closed__c')){
                opp.Cycle_Time_SIT_1_to_Closed__c = cycleTimeMap.get('Cycle_Time_SIT_1_to_Closed__c');
                opp.Competitor_Name__c = 'DCI';
            }
            opp.Project_Name__c = getFieldValues(fieldValueByFieldName, 'Project Name', 'Test Project' + i);
            if(listOfAccounts.size() >= numberOfRecords) {
                opp.AccountId = listOfAccounts[i].Id;
            }
            else if(listOfAccounts.size() == 1 && numberOfRecords > 1) {
                opp.AccountId = listOfAccounts[0].Id;
            }

            listOfTestOpportunities.add(opp);
        }

        if(isInsert) {
            insert listOfTestOpportunities;
        }

        return listOfTestOpportunities;
    }

    /**
    * @description method is used to check whether valueByFieldName Map contains field values, if yes then return value else null.
    * @param fieldValueByFieldName - Map<String, String>, sObject field value by Field API Name
    * @param fieldName - String, sObject field API name
    * @return String, field's value if map contains the field else null
    */
    private static String getFieldValues(Map<String, String> fieldValueByFieldName, String fieldName, String fieldValue) {
        if(fieldValueByFieldName != null && fieldValueByFieldName.containsKey(fieldName)) {
            return fieldValueByFieldName.get(fieldName);
        }

        return fieldValue;
    }

}