unpackaged/main/default/objects/Opportunity/fields/Competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name__c</fullName>
    <description>created for TAGCRM-128</description>
    <label>Competitor(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Survey Based Market Research(Kynetec)</fullName>
            </value>
            <value>
                <fullName>Survey Based Market Research(SPC)</fullName>
            </value>
            <value>
                <fullName>Premier Crop</fullName>
            </value>
            <value>
                <fullName>IN10T</fullName>
            </value>
            <value>
                <fullName>In-House Built Systems</fullName>
            </value>
            <value>
                <fullName>DCI</fullName>
            </value>
            <value>
                <fullName>AgCall</fullName>
            </value>
            <value>
                <fullName>Beck Ag</fullName>
            </value>
            <value>
                <fullName>AgData</fullName>
            </value>
            <value>
                <fullName>AgriTrend</fullName>
            </value>
            <value>
                <fullName>Smartwyre</fullName>
            </value>
            <value>
                <fullName>Aker</fullName>
            </value>
            <value>
                <fullName>Farmers Edge</fullName>
            </value>
            <value>
                <fullName>Taranis</fullName>
            </value>
            <value>
                <fullName>Decisive Farming</fullName>
            </value>
            <value>
                <fullName>Climate</fullName>
            </value>
            <value>
                <fullName>Retail FMS Systems</fullName>
            </value>
            <value>
                <fullName>One Soil</fullName>
            </value>
            <value>
                <fullName>EOS</fullName>
            </value>
            <value>
                <fullName>Authenticate</fullName>
            </value>
            <value>
                <fullName>FoodLogic</fullName>
            </value>
            <value>
                <fullName>Quadex</fullName>
            </value>
            <value>
                <fullName>iAuditor and Excel</fullName>
            </value>
            <value>
                <fullName>Excel</fullName>
            </value>
            <value>
                <fullName>ERP Systems</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>TraceOne</fullName>
            </value>
            <value>
                <fullName>Agriplace</fullName>
            </value>
            <value>
                <fullName>Food Experts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cycle_Time_SIT_1_to_Closed__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Time_SIT_1_to_Closed__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Days b/w SIT 1 to closed stage</description>
    <inlineHelpText>Days b/w SIT 1 to SIT 5 stage</inlineHelpText>
    <label>Cycle Time  SIT 1 to Closed</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cycle_Time_SIT_2_to_SIT_1__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Time_SIT_2_to_SIT_1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>created for TAGCRM-181</description>
    <inlineHelpText>Days b/w SIT 2 to SIT 1 stage</inlineHelpText>
    <label>Cycle Time  SIT 2 to SIT 1</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cycle_Time_SIT_3_to_SIT_2__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Time_SIT_3_to_SIT_2__c</fullName>
    <defaultValue>0</defaultValue>
    <description>created for TAGCRM-181</description>
    <inlineHelpText>Days b/w SIT 3 to SIT 2 stage</inlineHelpText>
    <label>Cycle Time  SIT 3 to SIT 2</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cycle_Time_SIT_4_to_SIT_3__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Time_SIT_4_to_SIT_3__c</fullName>
    <defaultValue>0</defaultValue>
    <description>created for TAGCRM-181</description>
    <inlineHelpText>Days b/w SIT 4 to SIT 3 stage</inlineHelpText>
    <label>Cycle Time  SIT 4 to SIT 3</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cycle_Time_SIT_5_to_SIT_4__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Time_SIT_5_to_SIT_4__c</fullName>
    <defaultValue>0</defaultValue>
    <description>created for TAGCRM-181</description>
    <inlineHelpText>Days b/w SIT 5 to SIT 4 stage</inlineHelpText>
    <label>Cycle Time  SIT 5 to SIT 4</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cycle_Time_SIT_6_to_SIT_5__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Time_SIT_6_to_SIT_5__c</fullName>
    <defaultValue>0</defaultValue>
    <description>created for TAGCRM-181</description>
    <inlineHelpText>Days b/w SIT 6 to SIT 5 stage</inlineHelpText>
    <label>Cycle Time  SIT 6 to SIT 5</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Deal_Lost_Reason_Comments__c.field-meta.xml
<CustomField>
    <fullName>Deal_Lost_Reason_Comments__c</fullName>
    <description>created for TAGCRM-558</description>
    <label>Lost Reason Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Last_Stage_Change__c.field-meta.xml
<CustomField>
    <fullName>Last_Stage_Change__c</fullName>
    <description>created for TAGCRM -178</description>
    <inlineHelpText>When opportunity stage is changed, Last Stage Change will be updated</inlineHelpText>
    <label>Last Stage Change</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reason__c</fullName>
    <description>Created for TAGCRM-558, lost opportunity reason</description>
    <label>Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Strategic Alignment &amp; Relationship</fullName>
            </value>
            <value>
                <fullName>Operation Sales Process</fullName>
            </value>
            <value>
                <fullName>Solution Fit</fullName>
            </value>
            <value>
                <fullName>Pricing &amp; Cost</fullName>
            </value>
            <value>
                <fullName>Invalid Opportunity (Exceptions Only)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lost_Reason_Details__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reason_Details__c</fullName>
    <description>Created for TAGCRM-558, detailed reasons for lost opportunity</description>
    <label>Lost Reason Details</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lost_Reason__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>L2R Experience with TELUS</fullName>
            </value>
            <value>
                <fullName>No Internal Support (Decision Maker)</fullName>
            </value>
            <value>
                <fullName>Status quo</fullName>
            </value>
            <value>
                <fullName>TELUS Brand Recognition/Reputation</fullName>
            </value>
            <value>
                <fullName>TELUS Ag Brand Recognition/Reputation</fullName>
            </value>
            <value>
                <fullName>TELUS Ag Partner Expertise</fullName>
            </value>
            <value>
                <fullName>Poor Sales Enablement Tools</fullName>
            </value>
            <value>
                <fullName>Poor TELUS Ag Operational Responsiveness</fullName>
            </value>
            <value>
                <fullName>Feature(s) Not Aligned to Customer Needs</fullName>
            </value>
            <value>
                <fullName>Footprint</fullName>
            </value>
            <value>
                <fullName>Lack of Demo/Technology Lab Support</fullName>
            </value>
            <value>
                <fullName>No Self-serve/Self-Install Capabilities</fullName>
            </value>
            <value>
                <fullName>Reliability (Network/Solution)</fullName>
            </value>
            <value>
                <fullName>Product Strategic Direction</fullName>
            </value>
            <value>
                <fullName>Transition Plan Poor or Missing</fullName>
            </value>
            <value>
                <fullName>Implementation Charges Too High</fullName>
            </value>
            <value>
                <fullName>Non-competitive Pricing</fullName>
            </value>
            <value>
                <fullName>Pricing Offer too Complex</fullName>
            </value>
            <value>
                <fullName>Switching/Migration Cost Too Expensive</fullName>
            </value>
            <value>
                <fullName>Duplicate of an Existing Opportunity</fullName>
            </value>
            <value>
                <fullName>Marketing Lead or Initiative Not Valid</fullName>
            </value>
            <value>
                <fullName>Other (See Notes)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/trac_OpportunityHelperTest.cls
/**
*******************************************************************************
* trac_OpportunityHelperTest  part of Telus Agri project
* @description this test class contains methods to test the methods of trac_OpportunitySelector class
* @author Neha Jain, Traction on Demand
* @date 2020-12-18
*
*******************************************************************************
*/
@isTest
public with sharing class trac_OpportunityHelperTest {

/**
    * @description creates test data for Opportunity and related objects using class trac_TestDataFactory
    * @return null
    */
    @testSetup static void setup() {
        //Inserting Accounts
        List<Account> listOfTestAccounts = trac_TestDataFactory.createTestAccounts(1, true, new Map<String, String>());
        Map<String,String> oppFieldMap = new Map<String, String>();
        Map<String,Decimal> cycleTimeMap = new Map<String, Decimal>();

        //Inserting Opportunities
        trac_TestDataFactory.createTestOpportunities(1, true, new Map<String, String>(), listOfTestAccounts,new Map<String, Decimal>() );

        oppFieldMap.put('Project Name','Project Name 5');
        oppFieldMap.put('Name','Name 5');
        oppFieldMap.put('StageName',trac_Constants.OPP_STAGE_SIT5_IDENTIFY_TARGET);
        cycleTimeMap.put('Cycle_Time_SIT_6_to_SIT_5__c',6);
        trac_TestDataFactory.createTestOpportunities(1, true, oppFieldMap, listOfTestAccounts,cycleTimeMap);
        oppFieldMap.put('Project Name','Project Name 4');
        oppFieldMap.put('Name','Name 4');
        cycleTimeMap.put('Cycle_Time_SIT_5_to_SIT_4__c',5);
        oppFieldMap.put('StageName',trac_Constants.OPP_STAGE_SIT4_CONFIRM_OPPORTUNITY);
        trac_TestDataFactory.createTestOpportunities(1, true, oppFieldMap, listOfTestAccounts,cycleTimeMap);

        oppFieldMap.put('Project Name','Project Name 3');
        oppFieldMap.put('Name','Name 3');
        oppFieldMap.put('StageName',trac_Constants.OPP_STAGE_SIT3_QUALIFY_OPPORTUNITY);
        cycleTimeMap.put('Cycle_Time_SIT_4_to_SIT_3__c',4);
        trac_TestDataFactory.createTestOpportunities(1, true, oppFieldMap, listOfTestAccounts,cycleTimeMap);

        oppFieldMap.put('Project Name','Project Name 2');
        oppFieldMap.put('Name','Name 2');
        oppFieldMap.put('StageName',trac_Constants.OPP_STAGE_SIT2_ADVOCATE_SOLUTION);
        cycleTimeMap.put('Cycle_Time_SIT_3_to_SIT_2__c',3);
        trac_TestDataFactory.createTestOpportunities(1, true, oppFieldMap, listOfTestAccounts,cycleTimeMap);

        oppFieldMap.put('Project Name','Project Name 1');
        oppFieldMap.put('Name','Name 1');
        oppFieldMap.put('StageName',trac_Constants.OPP_STAGE_SIT1_CLOSE_OPPORTUNITY);
        cycleTimeMap.put('Cycle_Time_SIT_2_to_SIT_1__c',2);
        trac_TestDataFactory.createTestOpportunities(1, true, oppFieldMap, listOfTestAccounts,cycleTimeMap);

        oppFieldMap.put('Project Name','Closed Project Name');
        oppFieldMap.put('Name','Name 0');
        oppFieldMap.put('StageName',trac_Constants.OPP_STAGE_CLOSED_LOST);
        cycleTimeMap.put('Cycle_Time_SIT_1_to_Closed__c',1);
        List<Opportunity> listOfOpportunities = trac_TestDataFactory.createTestOpportunities(1, false, oppFieldMap, listOfTestAccounts,cycleTimeMap);
        listOfOpportunities[0].Lost_Reason__c = 'Strategic Alignment & Relationship';
        listOfOpportunities[0].Lost_Reason_Details__c = 'Bankruptcy';
//        listOfOpportunities[0].Competitor_Name__c = 'DCI';
        listOfOpportunities[0].Deal_Lost_Reason_Comments__c = 'Lost';
        insert listOfOpportunities;


    }

    @isTest
    static void checkStageOrderTest() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity];
        try {
            for (Opportunity opportunity : listOfOpportunities) {
                opportunity.StageName = trac_Constants.OPP_STAGE_SIT1_CLOSE_OPPORTUNITY;
            }
            Test.startTest();
            update listOfOpportunities;
            Test.stopTest();
        } catch (Exception e) {
            System.assert(e.getMessage().contains(System.Label.Error_SkipOppStage), e.getMessage());
        }
    }

    @isTest
    static void insertCycleTimeWhenStageChangeForSIT5Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT6_REPOSITORY];
        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.Last_Stage_Change__c = System.now().addDays(-4);
        }
        update listOfOpportunities;
            for (Opportunity opportunity : listOfOpportunities) {
                opportunity.StageName = trac_Constants.OPP_STAGE_SIT5_IDENTIFY_TARGET;
            }
            Test.startTest();
            update listOfOpportunities;
            Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_6_to_SIT_5__c FROM Opportunity];
        System.assertEquals(4,newOppList[0].Cycle_Time_SIT_6_to_SIT_5__c);

    }

    @isTest
    static void insertCycleTimeWhenStageChangeForSIT4Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName,Cycle_Time_SIT_6_to_SIT_5__c,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_4_to_SIT_3__c,Cycle_Time_SIT_3_to_SIT_2__c,Cycle_Time_SIT_2_to_SIT_1__c,Cycle_Time_SIT_1_to_Closed__c FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT5_IDENTIFY_TARGET];
        System.debug('106::listOfOpportunities=='+listOfOpportunities);
        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.Last_Stage_Change__c = System.now().addDays(-10);
        }
        update listOfOpportunities;
        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT4_CONFIRM_OPPORTUNITY;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_6_to_SIT_5__c,Cycle_Time_SIT_4_to_SIT_3__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(10,newOppList[0].Cycle_Time_SIT_5_to_SIT_4__c);

    }
    @isTest
    static void insertCycleTimeWhenStageChangeForSIT5ReverseTest() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName,Cycle_Time_SIT_6_to_SIT_5__c,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_4_to_SIT_3__c,Cycle_Time_SIT_3_to_SIT_2__c,Cycle_Time_SIT_2_to_SIT_1__c,Cycle_Time_SIT_1_to_Closed__c FROM Opportunity
        Where StageName = :trac_Constants.OPP_STAGE_SIT5_IDENTIFY_TARGET];
        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.Last_Stage_Change__c = System.now().addHours(-4);
        }
        update listOfOpportunities;
        System.debug('129::reverse listOfOpportunities=='+listOfOpportunities);
        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT6_REPOSITORY;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_6_to_SIT_5__c,Cycle_Time_SIT_4_to_SIT_3__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_6_to_SIT_5__c);

    }

    @isTest
    static void insertCycleTimeWhenStageChangeForSIT3Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT4_CONFIRM_OPPORTUNITY];
        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.Last_Stage_Change__c = System.now().addDays(-4);
        }
        update listOfOpportunities;
        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT3_QUALIFY_OPPORTUNITY;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_6_to_SIT_5__c,Cycle_Time_SIT_4_to_SIT_3__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(4,newOppList[0].Cycle_Time_SIT_4_to_SIT_3__c);

    }

    @isTest
    static void insertCycleTimeWhenStageChangeForSIT4ReverseTest() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT4_CONFIRM_OPPORTUNITY];
        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.Last_Stage_Change__c = System.now().addHours(-4);
        }
        update listOfOpportunities;
        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT5_IDENTIFY_TARGET;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_6_to_SIT_5__c,Cycle_Time_SIT_4_to_SIT_3__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_5_to_SIT_4__c);

    }

    @isTest
    static void insertCycleTimeWhenStageChangeForSIT2Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT3_QUALIFY_OPPORTUNITY];
        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.Last_Stage_Change__c = System.now().addDays(-4);
        }
        update listOfOpportunities;
        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT2_ADVOCATE_SOLUTION;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_3_to_SIT_2__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(4,newOppList[0].Cycle_Time_SIT_3_to_SIT_2__c);

    }

    @isTest
    static void insertCycleTimeWhenStageChangeForSIT3Reverse1Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT3_QUALIFY_OPPORTUNITY];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT5_IDENTIFY_TARGET;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_6_to_SIT_5__c,Cycle_Time_SIT_4_to_SIT_3__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_5_to_SIT_4__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_4_to_SIT_3__c);

    }

    @isTest
    static void insertCycleTimeWhenStageChangeForSIT3Reverse2Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT3_QUALIFY_OPPORTUNITY];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT6_REPOSITORY;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_6_to_SIT_5__c,Cycle_Time_SIT_4_to_SIT_3__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_6_to_SIT_5__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_5_to_SIT_4__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_4_to_SIT_3__c);

    }

    @isTest
    static void insertCycleTimeWhenStageChangeForSIT1Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName,Competitor_Name__c FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT2_ADVOCATE_SOLUTION];
        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.Last_Stage_Change__c = System.now().addDays(-10);
        }
        update listOfOpportunities;
        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT1_CLOSE_OPPORTUNITY;
            opportunity.Competitor_Name__c = 'DCI';
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_2_to_SIT_1__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(10,newOppList[0].Cycle_Time_SIT_2_to_SIT_1__c);

    }
    @isTest
    static void insertCycleTimeWhenStageChangeForSIT2Reverse1Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT2_ADVOCATE_SOLUTION];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT3_QUALIFY_OPPORTUNITY;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_6_to_SIT_5__c,Cycle_Time_SIT_4_to_SIT_3__c,Cycle_Time_SIT_3_to_SIT_2__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_3_to_SIT_2__c);

    }
    @isTest
    static void insertCycleTimeWhenStageChangeForSIT2Reverse2Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT2_ADVOCATE_SOLUTION];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT4_CONFIRM_OPPORTUNITY;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_6_to_SIT_5__c,Cycle_Time_SIT_4_to_SIT_3__c,Cycle_Time_SIT_3_to_SIT_2__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_4_to_SIT_3__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_3_to_SIT_2__c);

    }
    @isTest
    static void insertCycleTimeWhenStageChangeForSIT2Reverse3Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT2_ADVOCATE_SOLUTION];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT5_IDENTIFY_TARGET;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_6_to_SIT_5__c,Cycle_Time_SIT_4_to_SIT_3__c,Cycle_Time_SIT_3_to_SIT_2__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_5_to_SIT_4__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_4_to_SIT_3__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_3_to_SIT_2__c);

    }

    @isTest
    static void insertCycleTimeWhenStageChangeForSIT2Reverse4Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT2_ADVOCATE_SOLUTION];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT6_REPOSITORY;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_6_to_SIT_5__c,Cycle_Time_SIT_4_to_SIT_3__c,Cycle_Time_SIT_3_to_SIT_2__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_6_to_SIT_5__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_5_to_SIT_4__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_4_to_SIT_3__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_3_to_SIT_2__c);

    }


    @isTest
    static void insertCycleTimeWhenStageChangeForClosedTest() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT1_CLOSE_OPPORTUNITY];
        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.Last_Stage_Change__c = System.now().addDays(-10);
        }
        update listOfOpportunities;
        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_CLOSED_LOST;
            opportunity.Lost_Reason__c = 'Strategic Alignment & Relationship';
            opportunity.Lost_Reason_Details__c = 'Bankruptcy';
            opportunity.Competitor_Name__c = 'None';
            opportunity.Deal_Lost_Reason_Comments__c = 'Lost';
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_1_to_Closed__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(10,newOppList[0].Cycle_Time_SIT_1_to_Closed__c);

    }
    @isTest
    static void insertCycleTimeWhenStageChangeForSIT1Reverse1Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT1_CLOSE_OPPORTUNITY];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT2_ADVOCATE_SOLUTION;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_2_to_SIT_1__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_2_to_SIT_1__c);

    }
    @isTest
    static void insertCycleTimeWhenStageChangeForSIT1Reverse2Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT1_CLOSE_OPPORTUNITY];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT3_QUALIFY_OPPORTUNITY;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_3_to_SIT_2__c,Cycle_Time_SIT_2_to_SIT_1__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_3_to_SIT_2__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_2_to_SIT_1__c);

    }
    @isTest
    static void insertCycleTimeWhenStageChangeForSIT1Reverse3Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT1_CLOSE_OPPORTUNITY];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT4_CONFIRM_OPPORTUNITY;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_4_to_SIT_3__c,Cycle_Time_SIT_3_to_SIT_2__c,Cycle_Time_SIT_2_to_SIT_1__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_4_to_SIT_3__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_3_to_SIT_2__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_2_to_SIT_1__c);

    }
    @isTest
    static void insertCycleTimeWhenStageChangeForSIT1Reverse4Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT1_CLOSE_OPPORTUNITY];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT5_IDENTIFY_TARGET;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_4_to_SIT_3__c,Cycle_Time_SIT_3_to_SIT_2__c,Cycle_Time_SIT_2_to_SIT_1__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_5_to_SIT_4__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_4_to_SIT_3__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_3_to_SIT_2__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_2_to_SIT_1__c);

    }

    @isTest
    static void insertCycleTimeWhenStageChangeForSIT1Reverse5Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_SIT1_CLOSE_OPPORTUNITY];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT6_REPOSITORY;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_6_to_SIT_5__c,Cycle_Time_SIT_4_to_SIT_3__c,Cycle_Time_SIT_3_to_SIT_2__c,Cycle_Time_SIT_2_to_SIT_1__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_6_to_SIT_5__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_5_to_SIT_4__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_4_to_SIT_3__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_3_to_SIT_2__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_2_to_SIT_1__c);

    }

    @isTest
    static void insertCycleTimeWhenStageChangeForClosedReverse1Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_CLOSED_LOST];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT1_CLOSE_OPPORTUNITY;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Cycle_Time_SIT_1_to_Closed__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_1_to_Closed__c);

    }
    @isTest
    static void insertCycleTimeWhenStageChangeForClosedReverse2Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_CLOSED_LOST];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT2_ADVOCATE_SOLUTION;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Cycle_Time_SIT_1_to_Closed__c,Cycle_Time_SIT_2_to_SIT_1__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_2_to_SIT_1__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_1_to_Closed__c);

    }
    @isTest
    static void insertCycleTimeWhenStageChangeForClosedReverse3Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_CLOSED_LOST];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT3_QUALIFY_OPPORTUNITY;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_3_to_SIT_2__c,Cycle_Time_SIT_2_to_SIT_1__c,Cycle_Time_SIT_1_to_Closed__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_3_to_SIT_2__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_2_to_SIT_1__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_1_to_Closed__c);

    }
    @isTest
    static void insertCycleTimeWhenStageChangeForClosedReverse4Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_CLOSED_LOST];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT4_CONFIRM_OPPORTUNITY;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_4_to_SIT_3__c,Cycle_Time_SIT_3_to_SIT_2__c,Cycle_Time_SIT_2_to_SIT_1__c,Cycle_Time_SIT_1_to_Closed__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_4_to_SIT_3__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_3_to_SIT_2__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_2_to_SIT_1__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_1_to_Closed__c);

    }
    @isTest
    static void insertCycleTimeWhenStageChangeForClosedReverse5Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_CLOSED_LOST];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT5_IDENTIFY_TARGET;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_4_to_SIT_3__c,Cycle_Time_SIT_3_to_SIT_2__c,Cycle_Time_SIT_2_to_SIT_1__c,Cycle_Time_SIT_1_to_Closed__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_5_to_SIT_4__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_4_to_SIT_3__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_3_to_SIT_2__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_2_to_SIT_1__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_1_to_Closed__c);

    }

    @isTest
    static void insertCycleTimeWhenStageChangeForClosedReverse6Test() {
        List<Opportunity> listOfOpportunities = [SELECT Id,Name,StageName FROM Opportunity Where StageName = :trac_Constants.OPP_STAGE_CLOSED_LOST];

        for (Opportunity opportunity : listOfOpportunities) {
            opportunity.StageName = trac_Constants.OPP_STAGE_SIT6_REPOSITORY;
        }

        Test.startTest();
        update listOfOpportunities;
        Test.stopTest();
        List<Opportunity> newOppList = [SELECT Id,StageName,Cycle_Time_SIT_5_to_SIT_4__c,Cycle_Time_SIT_6_to_SIT_5__c,Cycle_Time_SIT_4_to_SIT_3__c,Cycle_Time_SIT_3_to_SIT_2__c,Cycle_Time_SIT_2_to_SIT_1__c,Cycle_Time_SIT_1_to_Closed__c FROM Opportunity where id = :listOfOpportunities[0].Id];
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_6_to_SIT_5__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_5_to_SIT_4__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_4_to_SIT_3__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_3_to_SIT_2__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_2_to_SIT_1__c);
        System.assertEquals(0,newOppList[0].Cycle_Time_SIT_1_to_Closed__c);

    }
}